package <%= packageName %>.repository;

import <%= packageName %>.domain.<%= entityClass %>;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Generated by wakeup generator at <%= currentDT %>
 * 'http://wakeup.org.in'
 * <%= entityClass %> repository 
 */
public interface <%= entityClass %>Repository extends JpaRepository<<%= entityClass %>,Long> { }
