package <%= packageName %>.domain;

import java.util.Objects;
import javax.persistence.*;
import java.io.Serializable;

/**
 * Generated by wakeup generator at <%= currentDT %>
 * 'http://wakeup.org.in'
 * <%= entityClass %> entity 
 */
@Entity
@Table(name = "<%= entityTableName %>")
public class <%= entityClass %> implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;<% for (fieldId in fields) { %>
        
    @Column(name = "<%=fields[fieldId].fieldNameUnderscored %>")
    private <%= fields[fieldId].fieldType %> <%= fields[fieldId].fieldName %>;<% } %>
        
    public Long getId() { return id; }

    public void setId(Long id) { this.id = id; }<% for (fieldId in fields) { %>
        
    public <%= fields[fieldId].fieldType %> get<%= fields[fieldId].fieldInJavaBeanMethod %>() {
        return <%= fields[fieldId].fieldName %>;
    }

    public void set<%= fields[fieldId].fieldInJavaBeanMethod %>(<%= fields[fieldId].fieldType %> <%= fields[fieldId].fieldName %>) {
        this.<%= fields[fieldId].fieldName %> = <%= fields[fieldId].fieldName %>;
    }<% } %>

    @Override
    public boolean equals(Object o) {
        if (this == o) { return true; }
        if (o == null || getClass() != o.getClass()) { return false; }
        <%= entityClass %> <%= entityInstance %> = (<%= entityClass %>) o;
        if ( ! Objects.equals(id, <%= entityInstance %>.id)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "<%= entityClass %>{" +
            "id=" + id +<%_ for (fieldId in fields) { _%>
            ", <%= fields[fieldId].fieldName %>='" + <%= fields[fieldId].fieldName %> + "'" +<%_ } _%>
            '}';
    }
}
