import java.io.Serializable;

/**
 * Generated by wakeup generator at <%= currentDT %>
 * 'http://wakeup.org.in'
 * <%= stubClass %> stub 
 */
public class <%= stubClass %> implements Serializable {
    
    <% for (fieldId in fields) { %><% if(isPublic=='yes') { %>public<% } else { %>private<% } %> <%= fields[fieldId].fieldType %> <%= fields[fieldId].fieldName %>;                
    <% } %><% for (fieldId in fields) { %>   
    public <%= fields[fieldId].fieldType %> get<%= fields[fieldId].fieldInJavaBeanMethod %>() { return <%= fields[fieldId].fieldName %>; }

    public void set<%= fields[fieldId].fieldInJavaBeanMethod %>(<%= fields[fieldId].fieldType %> <%= fields[fieldId].fieldName %>) { this.<%= fields[fieldId].fieldName %> = <%= fields[fieldId].fieldName %>; }
   <% } %><% if (isBuilder) { %>
    public <%= stubClass %>() {}
    
    private <%= stubClass %>(Builder builder) {<% for (fieldId in fields) { %>
        <%= fields[fieldId].fieldName %> = builder.<%= fields[fieldId].fieldName %>;<% } %>
    }
    
    public static Builder newBuilder() {
        return new Builder();
    }
                             
    public static final class Builder {<% for (fieldId in fields) { %>
        private <%= fields[fieldId].fieldType %> <%= fields[fieldId].fieldName %>; <% } %>

        private Builder() {}
        <% for (fieldId in fields) { %>
        public Builder <%= fields[fieldId].fieldName %>(<%= fields[fieldId].fieldType %> <%= fields[fieldId].fieldName %>) {
            this.<%= fields[fieldId].fieldName %> = <%= fields[fieldId].fieldName %>;
            return this;
        }<% } %>
        public <%= stubClass %> build() { return new <%= stubClass %>(this); }
    }<% } %><% if (isToString) { %>
        
    @Override
    public String toString() {
        return "<%= stubClass %>{" +<%_ for (fieldId in fields) { _%>
            ", <%= fields[fieldId].fieldName %>='" + <%= fields[fieldId].fieldName %> + "'" +<%_ } _%>
            '}';
    }<% } %>
}
